### ISSUE TITLE
Multiple accounts?

### ISSUE THREAD

**Issue by MeGA-ct** [rabelloo/genshin-daily#2]
Hi,

I was looking at the other version README, 
https://github.com/takagg/genshin-impact-helper/blob/master/README.en-US.md
and there is support for multiple accounts.

I like your approach, but I'm not familiar with TypeScript nor the library's you are using, so I was wondering if it's possible to check with more than one account.

Thx.

**Comment by rabelloo** [comment]
The most obvious answer would be to create two GitHub accounts, but I suspect that's not the answer you want.

The only essential library I use is Cypress, which is made mainly for automated UI testing, the rest is just for code organization and stuff.
If you're interested you can take a look at that.
The main file in this repo is [/cypress/daily.spec.ts](https://github.com/rabelloo/genshin-daily/blob/main/cypress/daily.spec.ts), the rest is setup.

But I digress. Supporting multiple accounts is trivial.
**I just pushed a commit that should enable it**, please look at the [end of the updated Readme](https://github.com/rabelloo/genshin-daily#multiple-accounts) for instructions.

**Comment by MeGA-ct** [comment]
Thanks.

I checked daily.spec.ts, it's easy for me to understand what it's doing but as I said, I'm not familiar with TS.

Thanks again.
