### ISSUE TITLE
uncaught promise breaks the ci

### ISSUE THREAD

**Issue by rockmanvnx6** [rabelloo/genshin-daily#3]
```
  daily check-in
    1) should click today [cookie 1]


  0 passing (6s)
  1 failing

  1) daily check-in
       should click today [cookie 1]:
     CypressError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > 

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
  Error: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.
  
    > 
  
  When Cypress detects uncaught errors originating from your application it will automatically fail the current test.
  
  This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.
  
  https://on.cypress.io/uncaught-exception-from-application
  Error
  




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     6 seconds                                                                        │
  │ Spec Ran:     daily.spec.ts                                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /home/runner/work/genshin-daily/genshin-daily/cypress/screenshots/daily.spec.ts/    (1920x1080)
     daily check-in -- should click today [cookie 1] (failed).png                                   


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: /home/runner/work/genshin-daily/genshin-daily/cypress/video    (3 seconds)
                          s/daily.spec.ts.mp4                                                       


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  daily.spec.ts                            00:06        1        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     00:06        1        -        1        -        -  


Error: Cypress tests: 1 failed
```

**Comment by rabelloo** [comment]
Hi, the only non-Cypress code is just reading the `COOKIE` variable from the environment.

Are you sure you set its value correctly as instructed?

![image](https://user-images.githubusercontent.com/18623773/120921348-29f46a80-c6bb-11eb-8d55-e565425e9c64.png)

Make sure you followed all the instructions in [the readme](https://github.com/rabelloo/genshin-daily#readme)

After double checking it's been setup correctly and there's no typo or anything, if the issue persists let me know.

**Comment by rockmanvnx6** [comment]
![image](https://user-images.githubusercontent.com/16440123/120929075-e9ccd080-c72a-11eb-8784-946210384cca.png)

Hi there,

I've named as COOKIE in the secrets and simply pasted it into the value field. I tried to manually run again but the error still occurs.

**Comment by rockmanvnx6** [comment]
![image](https://user-images.githubusercontent.com/16440123/121003973-76ca6500-c7d1-11eb-9ea9-2f4e6fe03a31.png)
does this code assume user to have their own avatar instead of the default one?

**Comment by rockmanvnx6** [comment]
I have made a few modification for my CI to work:

1. Cypress will auto stop if it detects an uncaught exception from the webpage. Which in some case could be the front end issue. 

![image](https://user-images.githubusercontent.com/16440123/121006797-a9299180-c7d4-11eb-8d56-5c7a5f614b19.png)

https://docs.cypress.io/guides/references/error-messages#Uncaught-exceptions-from-your-application

To prevent this, I added this on top to not stop if it detects any exception.

```
Cypress.on('uncaught:exception', (err, runnable) => {
  return false;
});
```

2. 

```
// wait for data to finish loading
cy.get('[class*=avatar] img', { timeout: 30000 })
    .should('have.attr', 'src')
    .and('not.include', 'webstatic-sea');
```

This code fails in my test as my default avatar includes "webstatic-sea". To fix this, i instead check if all the check-in items are loaded:

```
cy.get('[class*=__sign-content_---list]', { timeout: 30000 })
    .should('not.be.empty');
```

Not sure if those are good fixes but they work on my account.

**Comment by rabelloo** [comment]
> does this code assume user to have their own avatar instead of the default one?

It does indeed, that's how it knows it's finished loading.

Great job on the debugging, it totally makes sense to prevent uncaught exceptions to stop Cypress, indeed the website itself could fail.

I'll have to double check the other condition (list not empty) works every time but it looks solid, much better than checking for the avatar.

Thanks for finding this, I'll update the main branch soon to make sure your fixes are available for everyone.

**Comment by rabelloo** [comment]
Unfortunately at one point the list is not empty but not all data has been loaded yet.
Depending on internet speed that check could fail.

However we can intercept the API call and wait until it's finished to click the appropriate item.

I have pushed new commits that should hopefully make the entire thing more robust and just overall better for everyone.

Would you mind fetching the upstream on your fork to ensure it works for you?

**Comment by rockmanvnx6** [comment]
when i tested it for the first time with manual run on Github Action, CI worked but it didn't check in. I downloaded it and ran locally it checked in. I'll follow up on this tomorrow to see if the CI runs correctly.

**Comment by rockmanvnx6** [comment]
hey there, when testing with github CI it doesn't work for some reason. There is no error throw, however it does not check in. It clicks on the "active" class but then nothing happens.

**Comment by rabelloo** [comment]
I think waiting on that API call might not be enough. I'll see what other checks I can add to make it more robust and let you know once it's ready. Thanks again for checking.

**Comment by rabelloo** [comment]
There, I'm waiting on both API calls, they seem to have one for event data and another for account data.

From my tests only the event data seemed relevant but, nonetheless, waiting on both is not a big deal.

Let me know if it works for you now, will probably have to wait until tomorrow.

**Comment by rockmanvnx6** [comment]
Hey there it is still not working. I think it's only my account problem, for some reason it doesn't work. It works for my friend's account. 

I tried to listen to /community/user/wapi/getUserFullInfo as well but it doesn't work either. When testing locally it works but for some reasons the Github Action is not working.

If you don't mind, I can email you my cookie for debugging purposes.

**Comment by rabelloo** [comment]
I wouldn't advise sharing private information with anyone online, especially not over e-mail, that's not safe 🙈

I'm happy to help, don't get me wrong.

It seems that your latest run passed successfully:
https://github.com/rockmanvnx6/genshin-daily/runs/2792429973?check_suite_focus=true
Looks like you deleted your fork and re-forked it from scratch.

Are you sure it doesn't work?

Let it run automatically today, I'll keep an eye.
If it doesn't work I can open a PR on your fork and we can test stuff out without me knowing your cookie.

**Comment by rockmanvnx6** [comment]
I'm happy to encrypt it with your public key if you have one. The account doesn't have much stuff so I don't mind loosing it haha. 

> Are you sure it doesn't work?

yes, CI passes all test but it doesn't actually check in. When testing it locally, tests work and check-in works. Howerver, on Github, tests work but it doesn't work.

It's really weird. When I tested with 

```
  cy.get('body')
        .then(($body) => {
          // find the target
          const active = $body.find('[class*=active]');

          // if there's an active day, use that
          if (active.length) return active;

          return active;
        })
        .click();
```

which forced it to click on the active day to check in, the CI tests passed but the check in doesn't work (when visiting the website again - the active day isn't checked in. And in game doesn't have check-in reward)

**Comment by rockmanvnx6** [comment]
I figured out the problem, it's the cookie issue. So my account has the old cookie format where it doesn't have `login_ticket=`. So after updating my nickname (the cause of the avatar error), I have to logout and relogin again to get `login_ticket=`

**Comment by rabelloo** [comment]
Good to hear, glad it works now.
